# Generated by Django 3.2.8 on 2021-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_is_remember'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='secret_code',
            field=models.TextField(default=0),
        ),
    ]
