# Generated by Django 3.2.8 on 2021-11-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='secret_code',
            field=models.TextField(),
        ),
    ]
