# Generated by Django 3.2.8 on 2021-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_num', models.IntegerField()),
                ('category_num', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('kakao_url', models.TextField()),
                ('review', models.IntegerField()),
                ('rate', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
